### ISSUE TITLE
pretained part does not work in my computer

### ISSUE THREAD

**Issue by mauimoana** [Xovee/ccgl#1]
Hello Dr. Xovee, I encountered an error when running the pretraining section of your code. I was wondering if there is a bug in the code you provided in the pretrainning part or if there is an issue with my own GPU server. 

![image](https://github.com/Xovee/ccgl/assets/77086328/356940cb-d6ee-4db1-aa08-e8c4888222c2)

Thanks you.

**Comment by Xovee** [comment]
deep regret for using tensorflow... it is a shit. 

previously the codes run without bugs, now it seems more like the tensorflow (specific versions) is not working with your GPUs. 

try to upgrade tensorflow to newer versions.

**Comment by Xovee** [comment]
**Update**:

![image](https://github.com/Xovee/ccgl/assets/25814962/8cc793c3-bb25-4467-a890-df3243d32002)

> Note: The error message "Status: device kernel image is invalid" indicates that the TensorFlow package does not contain PTX for your architecture. You can enable compute capabilities by [building TensorFlow from source](https://www.tensorflow.org/install/source).

I found this in the Tensorflow website, you may try to build the tensorflow from source. 

Link: https://www.tensorflow.org/install/source

**Comment by mauimoana** [comment]
Thank very much for your reply. Wish you better luck next time ！
